apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCGOPqObwJi3TEtGgfs0AXSrh/+QjRnbGrgHLgxkda6cYQMimzkhIwuNVkViCOrbmJNN8vbodaGj/99cJAAGBMBiVRpFIthKiqOq+/y7HmGQeI3ajUv1VkW+KHRMppdbxuwz3UmJAC9CcK7s1kbahMmXnP//IV7b764ZTOd4zAvZ21EW0subSL2ElGPPzfDt8vhqdFj8H3zyJzPNDUKfK5VZF+WfN+XvXbg+hAbiH19K5aqwmBAP23p4royJatEDXunTi8Z+xj/fnWF0OFdtRe9uwRbSLrgJXMQ/Rn5m1hBFwYiy7DIMiASFR8AZU41zJ+XXgtlGSNfC7LLcKRg6xiJHBrMfx9weqQmVZFX6FflgA/GnkmYBvs0AZH4nIMy7hqiednOG58ytBkrHhQpQtq9VEACdGywt9geX/0BZed0BZCr2mrdoY2ylpioF82EUJcXsmZsZc8NLgU/4UTO6byflYXvxxPWzee5QeD57LoY4ZEyOO3+W7Lt59nXrHm5HF4HKtXH45IwJ/NVFsgaPvNumzsQgIkdaGWcaHre06Qmydjqb4iEGqX1t/wLCChJsAsaBbqYTOsXgjnrYeuuhXk5vM159rbw/vyCO5aFxYNqlO7V8TGkzi4mAynNE5LyN/5wvSzHjJvyqq7kd2+4uZHd39QiQ4jQ4tPNzPhrPfmiBkVPnb25XLbqJkvPH2qWsKa7a8V1JCprVQzTYHx6JADMavzGA+LXV2QZvDCBMQNhvhr/XNGZr7ir
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

